config/routes.rb
Connector::Application.routes.draw do
  root :to => 'users#home'

  resources :groups
  match '/groups/:group_id/members', :to => 'groups#add_member', :via => :post
  match '/groups/:group_id/members/:person_id', :to => 'groups#update_member', :via => :put
  match '/groups/:group_id/members/:person_id', :to => 'groups#remove_member', :via => :delete

  resources :regions

  resources :messages, :except => :show

  resources :people
  match '/people/:person_id/groups', :to => 'people#add_to_group', :via => :post
  match '/people/:person_id/groups/:group_id', :to => 'people#remove_from_group', :via => :delete

  resources :tasks
  match '/tasks/:task_id/notes', :to => 'tasks#add_note', :via => :post

  resources :task_types do
    resources :sub_task_types
  end

  resources :users do
    member do
      get 'password'
      post 'reset_password'
    end
  end
  match '/home', :to => 'users#home'
  match '/todo', :to => 'users#todo', :via => :get
  match '/email_overdue', :to => 'tasks#overdue', :via => :get

  resources :sessions, :only => [ :new, :create, :destroy ]
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'

end

app/controllers/task_types_controller.rb
class TaskTypesController < ApplicationController
  before_filter :require_logged_in_admin

  # GET /task_types
  # GET /task_types.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: TaskType.all }
    end
  end

  # GET /task_types/1
  # GET /task_types/1.json
  def show
    @task_type = TaskType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task_type }
    end
  end

  # GET /task_types/new
  # GET /task_types/new.json
  def new
    @task_type = TaskType.new
    2.times { @task_type.task_statuses.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task_type }
    end
  end

  # GET /task_types/1/edit
  def edit
    @task_type = TaskType.find(params[:id])
  end

  # POST /task_types
  # POST /task_types.json
  def create
    @task_type = TaskType.new(params[:task_type])

    respond_to do |format|
      if @task_type.save
        format.html { redirect_to @task_type, notice: 'Task type was successfully created.' }
        format.json { render json: @task_type, status: :created, location: @task_type }
      else
        format.html { render action: "new" }
        format.json { render json: @task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /task_types/1
  # PUT /task_types/1.json
  def update
    @task_type = TaskType.find(params[:id])

    respond_to do |format|
      if @task_type.update_attributes(params[:task_type])
        format.html { redirect_to @task_type, notice: 'Task type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_types/1
  # DELETE /task_types/1.json
  def destroy
    @task_type = TaskType.find(params[:id])
    @task_type.destroy

    respond_to do |format|
      format.html { redirect_to task_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/task_types_helper.rb
module TaskTypesHelper
end

app/views/task_types/_form.html.erb
<%= form_for(@task_type) do |f| %>
  <% if @task_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_type.errors.count, "error") %> prohibited this task_type from being saved:</h2>

      <ul>
      <% @task_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description, 'What is the goal of this kind of task? (e.g., "Connect to a Community Group")' %><br />
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :title_template, 'How this task should appear in page titles (e.g., "Connect <name> to a Community Group"). <name> will be replaced with the person\'s name.' %><br />
    <%= f.text_field :title_template%>
  </div>

  <div class="field">
    <%= f.label :group_type_id, 'What kind of group this applies to:' %>
    <%= f.collection_select :group_type_id, GroupType.all, :id, :description, :include_blank => true %>
  </div>

  <div class="grouping_box">
    <p>Possible statuses that this type of task may have:</p>
    <%= f.fields_for :task_statuses do |builder| %>
      <%= render 'task_status_fields', :f => builder %>
    <% end %>
    <%= link_to_add_field "[new]", f, :task_statuses, :class => :action %>

    <p>
      The "status" of a task describes where the task is, in its progression from start to finish. A newly-created task
      begins having the <b>start</b> status, and remains in-progress until it reaches a <b>finish</b> status; at that
      point, the task is done.
    </p>
    <p>
      There must be exactly one <b>start</b> status. Also, there must be at least one <b>finish</b> status (otherwise,
      the task could never end), but there may be more than one (for example, there could be <b>finish</b> statuses of
      "successfully connected" and "person not responsive", both of which would end the task).
    </p>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_types/_task_status_fields.html.erb
<div class="field">
  <%= f.text_field :description %>
  <%= f.check_box :start  %> <%= f.label :start  %>
  <%= f.check_box :finish %> <%= f.label :finish %>
  <%= link_to_delete_field "[delete]", f, '.field', :class => :action %>
</div>

app/views/task_types/edit.html.erb
<% provide(:title, "Edit task type: #{@task_type.description}") %>

<%= render 'form' %>

<%= link_to '[cancel edit]', @task_type, :class => :action %> |
<%= link_to '[go back to task type list]', task_types_path, :class => :action %>

app/views/task_types/index.html.erb
<% provide(:title, 'Listing task types') %>
<p><%= link_to '[create new task type]', new_task_type_path, :class => :action %></p>

<table class="index_table">
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <% if logged_in_super_admin? %>
      <th></th>
    <% end %>
  </tr>

<% TaskType.order(:description).all.each do |task_type| %>
  <tr>
    <td><%= link_to task_type.description, task_type %></td>
    <td><%= link_to '[edit]', edit_task_type_path(task_type), :class => :action %></td>
    <% if logged_in_super_admin? %>
      <td><%= link_to '[destroy]', task_type, confirm: 'This will obliterate this record from the database...are you sure?', :method => :delete, :class => :action %></td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/task_types/new.html.erb
<% provide(:title, 'Create new task type') %>

<%= render 'form' %>

<%= link_to '[go back to task type list]', task_types_path, :class => :action %>

app/views/task_types/show.html.erb
<% provide(:title, "Task type: #{@task_type.description}") %>

<div>
  <b>Example title:</b> "<%= @task_type.title_template.sub(/<name>/, 'John Smith') %>"
</div>

<div>
  <b>Relevant to:</b> <%= @task_type.group_type.description %>
</div>

<br />

<div>
  Possible statuses of this task:
  <ul>
    <% sub_task_types = @task_type.sub_task_types.where(:task_status_id => nil) %>
    <% if !sub_task_types.empty? %>
      <li><i>Task start</i>
        <ul>
          <% sub_task_types.each do |stt| %>
            <li><%= stt.description %></li>
          <% end %>
        </ul>
      </li>
    <% end %>

    <% @task_type.task_statuses.each do |ts| %>
      <li>
        <%= ts.description %>
        <% if ts.start? %><b>[start]</b><% end %>
        <% if ts.finish? %><b>[finish]</b><% end %>
        
        <% sub_task_types = @task_type.sub_task_types.where(:task_status_id => ts.id) %>
        <% if !sub_task_types.empty? %>
          <ul>
            <% sub_task_types.each do |stt| %>
              <li><%= stt.description %></li>
            <% end %>
          </ul>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>


<%= link_to '[edit this task type]', edit_task_type_path(@task_type), :class => :action %> |
<%= link_to '[show sub-task types]', task_type_sub_task_types_path(@task_type), :class => :action %> |
<%= link_to '[go back to task type list]', task_types_path, :class => :action %>