config/routes.rb
Connector::Application.routes.draw do
  root :to => 'users#home'

  resources :groups
  match '/groups/:group_id/members', :to => 'groups#add_member', :via => :post
  match '/groups/:group_id/members/:person_id', :to => 'groups#update_member', :via => :put
  match '/groups/:group_id/members/:person_id', :to => 'groups#remove_member', :via => :delete

  resources :regions

  resources :messages, :except => :show

  resources :people
  match '/people/:person_id/groups', :to => 'people#add_to_group', :via => :post
  match '/people/:person_id/groups/:group_id', :to => 'people#remove_from_group', :via => :delete

  resources :tasks
  match '/tasks/:task_id/notes', :to => 'tasks#add_note', :via => :post

  resources :task_types do
    resources :sub_task_types
  end

  resources :users do
    member do
      get 'password'
      post 'reset_password'
    end
  end
  match '/home', :to => 'users#home'
  match '/todo', :to => 'users#todo', :via => :get
  match '/email_overdue', :to => 'tasks#overdue', :via => :get

  resources :sessions, :only => [ :new, :create, :destroy ]
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'

end

app/controllers/sub_task_types_controller.rb
class SubTaskTypesController < ApplicationController
  # GET /task_types/1/sub_task_types
  # GET /task_types/1/sub_task_types.json
  def index
    @task_type = TaskType.find(params[:task_type_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @task_type.sub_task_types.all }
    end
  end

  # GET /task_types/1/sub_task_types/1
  # GET /task_types/1/sub_task_types/1.json
  def show
    @task_type = TaskType.find(params[:task_type_id])
    @sub_task_type = @task_type.sub_task_types.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sub_task_type }
    end
  end

  # GET /task_types/1/sub_task_types/new
  # GET /task_types/1/sub_task_types/new.json
  def new
    @task_type = TaskType.find(params[:task_type_id])
    @sub_task_type = @task_type.sub_task_types.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sub_task_type }
    end
  end

  # GET /task_types/1/sub_task_types/1/edit
  def edit
    @task_type = TaskType.find(params[:task_type_id])
    @sub_task_type = @task_type.sub_task_types.find(params[:id])
  end

  # POST /task_types/1/sub_task_types
  # POST /task_types/1/sub_task_types.json
  def create
    @task_type = TaskType.find(params[:task_type_id])
    @sub_task_type = SubTaskType.new(params[:sub_task_type])
    @task_type.sub_task_types << @sub_task_type

    respond_to do |format|
      if @sub_task_type.save
        format.html { redirect_to [@task_type, @sub_task_type], notice: 'Sub task type was successfully created.' }
        format.json { render json: @sub_task_type, status: :created, location: @sub_task_type }
      else
        format.html { render action: "new" }
        format.json { render json: @sub_task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /task_types/1/sub_task_types/1
  # PUT /task_types/1/sub_task_types/1.json
  def update
    @task_type = TaskType.find(params[:task_type_id])
    @sub_task_type = @task_type.sub_task_types.find(params[:id])

    respond_to do |format|
      if @sub_task_type.update_attributes(params[:sub_task_type])
        format.html { redirect_to [@task_type, @sub_task_type], notice: 'Sub task type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sub_task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_types/1/sub_task_types/1
  # DELETE /task_types/1/sub_task_types/1.json
  def destroy
    @task_type = TaskType.find(params[:task_type_id])
    @sub_task_type = @task_type.sub_task_types.find(params[:id])
    @sub_task_type.destroy

    respond_to do |format|
      format.html { redirect_to task_type_sub_task_types_url(@task_type) }
      format.json { head :no_content }
    end
  end
end

app/helpers/sub_task_types_helper.rb
module SubTaskTypesHelper
end

app/views/sub_task_types/_form.html.erb
<%= form_for([@task_type, @sub_task_type]) do |f| %>
  <% if @sub_task_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub_task_type.errors.count, "error") %> prohibited this sub_task_type from being saved:</h2>

      <ul>
      <% @sub_task_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br />
    <%= f.text_area :instructions, :rows => 4, :cols => 80 %>
  </div>
  <div class="field">
    <%= f.label :contact_within_days, 'Attempt contact within' %>
    <%= f.select :contact_within_days, 1..30, :include_blank => true %>
    <%= f.label :contact_within_days, 'days' %>
  </div>
  <div class="field">
    <%= f.label :contact_attempts_to_make, 'Make at least' %>
    <%= f.select :contact_attempts_to_make, 1..30, :include_blank => true %>
    <%= f.label :contact_attempts_to_make, 'consecutive attempts to contact' %>
  </div>
  <div class="field">
    <%= f.label :task_status, 'Create when parent task first enters the' %>
    <%= f.collection_select :task_status_id, @task_type.task_statuses, :id, :description, :include_blank => true %>
    <%= f.label :task_status, 'state (blank for parent task creation)' %>
  </div>
  <div class="field">
    <%= f.check_box :active %> <%= f.label :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sub_task_types/edit.html.erb
<% provide(:title, "[#{@task_type.description}] Editing sub-task type #{@sub_task_type.description}") %>

<%= render 'form' %>

<%= link_to '[go back to sub-task type]', task_type_sub_task_type_path([@task_type, @sub_task_type]), :class => :action %> |
<%= link_to '[go back to sub-task type list]', task_type_sub_task_types_path(@task_type), :class => :action %> |
<%= link_to '[go back to task type]', task_type_path(@task_type), :class => :action %>

app/views/sub_task_types/index.html.erb
<% provide(:title, "[#{@task_type.description}] Listing sub-task types") %>
<p><%= link_to '[create new sub-task type]', new_task_type_sub_task_type_path(@task_type), :class => :action %></p>

<% if !@task_type.sub_task_types.where(:active => true).empty? %>
  <table class="index_table">
    <tr>
      <th>Description</th>
      <th>Created when</th>
      <th></th>
      <% if logged_in_super_admin? %>
        <th></th>
      <% end %>
    </tr>

    <% @task_type.sub_task_types.each do |stt| %>
      <tr>
        <td><%= link_to stt.description, [@task_type, stt] %></td>
        <td><%= stt.task_status.nil? ? 'Task starts' : "Task becomes '#{stt.task_status.description}'" %></td>
        <td><%= link_to '[edit]', edit_task_type_sub_task_type_path(@task_type, stt), :class => :action %></td>
        <% if logged_in_super_admin? %>
          <td><%= link_to '[destroy]', task_type_sub_task_type_path(@task_type, stt), confirm: 'This will obliterate this record from the database...are you sure?', :method => :delete, :class => :action %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>No sub-task types are defined yet. Create one?</p>
<% end %>

<%= link_to '[back to task type]', task_type_path(@task_type), :class => :action %>

app/views/sub_task_types/new.html.erb
<% provide(:title, "[#{@task_type.description}] Create new sub-task type") %>

<%= render 'form' %>

<%= link_to '[go back to sub-task type list]', task_type_sub_task_types_path(@task_type), :class => :action %> |
<%= link_to '[go back to task type]', task_type_path(@task_type), :class => :action %>

app/views/sub_task_types/show.html.erb
<% provide(:title, "[#{@task_type.description}] #{@sub_task_type.description}") %>

<p>
  <b>Instructions:</b>
  <%= format_plain_text @sub_task_type.instructions %>
</p>

<p>
  <b>Created:</b>
  <% if !@sub_task_type.task_status.nil? %>
    when the parent task first enters the <i><%= @sub_task_type.task_status.description %></i> state
  <% else %>
    when the parent task is created
  <% end %>
</p>

<% if !@sub_task_type.contact_within_days.nil? %>
  <p><b>Contact within <%= pluralize(@sub_task_type.contact_within_days, 'day') %></b></p>
<% end %>

<% if !@sub_task_type.contact_attempts_to_make.nil? %>
  <p><b>Make at least <%= pluralize(@sub_task_type.contact_attempts_to_make, 'attempt') %> to contact</b></p>
<% end %>

<p>
  <b>Active:</b>
  <%= @sub_task_type.active ? 'Yes' : 'No' %>
</p>

<%= link_to '[edit]', edit_task_type_sub_task_type_path(@task_type, @sub_task_type), :class => :action %> |
<%= link_to '[go back to sub-task type list]', task_type_sub_task_types_path(@task_type), :class => :action %> |
<%= link_to '[go back to task type]', task_type_path(@task_type), :class => :action %>