config/routes.rb
Connector::Application.routes.draw do
  root :to => 'users#home'

  resources :groups
  match '/groups/:group_id/members', :to => 'groups#add_member', :via => :post
  match '/groups/:group_id/members/:person_id', :to => 'groups#update_member', :via => :put
  match '/groups/:group_id/members/:person_id', :to => 'groups#remove_member', :via => :delete

  resources :regions

  resources :messages, :except => :show

  resources :people
  match '/people/:person_id/groups', :to => 'people#add_to_group', :via => :post
  match '/people/:person_id/groups/:group_id', :to => 'people#remove_from_group', :via => :delete

  resources :tasks
  match '/tasks/:task_id/notes', :to => 'tasks#add_note', :via => :post

  resources :task_types do
    resources :sub_task_types
  end

  resources :users do
    member do
      get 'password'
      post 'reset_password'
    end
  end
  match '/home', :to => 'users#home'
  match '/todo', :to => 'users#todo', :via => :get
  match '/email_overdue', :to => 'tasks#overdue', :via => :get

  resources :sessions, :only => [ :new, :create, :destroy ]
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  self.primary_key = :person_id

  attr_accessible :username, :password, :password_confirmation, :must_change_password, :welcome_email_sent, :remember_token, :active, :admin, :person_attributes
  belongs_to :person, :dependent => :destroy
  has_many :groups
  has_many :group_memberships, :foreign_key => :person_id
  has_many :tasks, :through => :group_memberships
  has_secure_password

  # Returns the collection of tasks assigned to this user that are currently in-progress
  def in_progress_tasks
    Task.joins('INNER JOIN group_memberships ON tasks.contact_id = group_memberships.id').joins('INNER JOIN task_statuses ON tasks.task_status_id = task_statuses.id').where('group_memberships.person_id' => id, 'task_statuses.finish' => false).order('created_at DESC')
  end

  def tasks
    super.order('created_at DESC')
  end

  # Save usernames as all lower-case, to ensure that the uniqueness constraint
  # is enforced regardless of whether the database cares about case
  before_save { |user| user.username = username.downcase }
  before_save :create_remember_token

  accepts_nested_attributes_for :person

  validates :person, :presence => true
  validates :username, :presence => true, :uniqueness => { :case_sensitive => false }
  validate :has_email
#  validates :password, :length => { :minimum => 4 }
#  validates :password_confirmation, :presence => true

  def id
    self.person_id
  end

  def name
    self.person.name
  end

  def phone
    self.person.phone
  end

  def email
    self.person.email
  end

  def address
    self.person.address
  end

  def member?
    self.person.member?
  end

  # Build objects for any missing associations
  def build_if_missing
    if self.person.nil?
      self.build_person
    end
    self.person.build_if_missing
  end

  # Static method to sanitze an attributes hash destined for update_attributes
  def self.sanitize_attributes(user_attributes)
    if !user_attributes.nil?
      Person.sanitize_attributes user_attributes[:person_attributes]
    end
    return false # Don't delete me
  end

private
  # Create a random token for allowing the user's browser to "remember me"
  def create_remember_token
    if self.remember_token.nil?
      self.remember_token = SecureRandom.urlsafe_base64
    end
  end

  def has_email
    if self.person.email.blank?
      errors.add(:email, 'In order to make this person a user, the email address must not be blank.')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_authenticated_user, :only => [:update, :password]
  before_filter :require_logged_in_admin, :only => [:new, :create, :destroy, :reset_password]
  before_filter :require_current_user_or_admin, :only => [:update, :password]
  before_filter :require_logged_in_user, :except => [:update, :password]

  # GET /
  def home
    respond_to do |format|
      format.html # home.html.erb
    end
  end

  # GET /users/1/password
  def password
    @user = User.find(params[:id])
  end

  # POST /users/1/reset_password
  def reset_password
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.person.reset_password_and_send_mail
        format.html { redirect_to @user, notice: 'Password successfully reset.' }
        format.json { head :no_content }
      else
        format.html { redirect_to @user }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /users
  # GET /users.xlsx
  # GET /users.json
  def index
    @query = UsersQuery.new(params[:query])
    @users = @query.find

    respond_to do |format|
      format.html # index.html.erb
      format.xlsx # index.xlsx.axlsx
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @user.build_if_missing

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @user.build_if_missing
  end

  # POST /users
  # POST /users.json
  def create

    # If no password was provided, default to the username, but require the user to change on next login
    if !params[:user][:username].blank? &&
        params[:user][:password].blank? &&
        params[:user][:password_confirmation].blank?
      params[:user][:password] = params[:user][:username]
      params[:user][:password_confirmation] = params[:user][:username]
      params[:user][:must_change_password] = true
    end

    User.sanitize_attributes params[:user]

    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { @user.build_if_missing; render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    # Non-admins shouldn't be able to make themselves admins...that would be less than awesome
    if !logged_in_admin?
      params[:user][:admin] = false
    end

    User.sanitize_attributes params[:user]

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { @user.build_if_missing; render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  # GET /todo
  def todo
  end

private
  # Only admins get access to users besides themselves
  def require_current_user_or_admin
    if !current_user.admin
      redirect_to home_path, :notice => 'Only administrators may edit other people\'s user accounts' unless current_user.id == params[:id].to_i
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.fields_for :person do |builder| %>
    <%= render 'shared/person_fields', :f => builder %>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>

  <% if logged_in_admin? %>
    <div class="field">
      <%= f.check_box :active %>
      <%= f.label :active, 'Active user' %>
    </div>
    <div class="field">
      <%= f.check_box :admin %>
      <%= f.label :admin, 'Administrator' %>
    </div>
  <% else %>
    <%= f.hidden_field :active %>
    <%= f.hidden_field :admin %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_query.html.erb
<div class="search_box">
  <div class="term_dashboard" onclick="$('.search_form').toggle()">
    <h2>Click here to search, filter &amp; sort</h2>

    <% if !query.order_by.blank? %>
      <span class="term order">Sort by: <%= query.order_by %></span>
    <% end %>
    <% if !query.active.blank? %>
      <span class="term filter">Active: <%= query.active %></span>
    <% end %>
    <% if !query.name_like.blank? %>
      <span class="term filter">Name like: "<%= query.name_like %>"</span>
    <% end %>
    <% if !query.username_like.blank? %>
      <span class="term filter">Username like: "<%= query.username_like %>"</span>
    <% end %>
  </div>

  <div class="search_form">
    <%= form_for query, :as => :query, :url => users_path, :method => :get do |f| %>
      <div class="field">
        <%= f.label :order_by, 'Sort by' %>
        <%= f.select :order_by, options_for_select(UsersQuery::sortable_fields, query.order_by) %>
      </div>
      <div class="field">
        <%= f.label :active %>
        <%= f.select :active, options_for_select(['yes', 'no'], query.active), :include_blank => true %>
      </div>
      <div class="field">
        <%= f.label :name_like %>
        <%= f.text_field :name_like %>
      </div>
      <div class="field">
        <%= f.label :username_like %>
        <%= f.text_field :username_like %>
      </div>
      <%= f.submit 'Update' %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user: #{@user.name}") %>

<%= render 'form' %>

<%= link_to '[cancel edit]', @user, :class => :action %> |
<%= link_to '[change password]', password_user_path(@user), :class => :action %> |
<%= link_to '[go back to user list]', users_path, :class => :action %>

app/views/users/home.html.erb
<% provide(:title, "Welcome, #{current_user.name}") %>

<% show_finished = params[:show_finished] == 'true' %>
<% tasks = show_finished ? current_user.tasks : current_user.in_progress_tasks %>
<div class="grouping_box">
  <h2>My tasks</h2>
  <b>Showing <%= show_finished ? "all tasks" : "in-progress tasks" %></b>
  <%= link_to ( show_finished ? "[see only in-progress tasks]" : "[see finished tasks too]" ), home_path(:show_finished => !show_finished ), :class => :action %>
  <br />
  <% if tasks.empty? %>
    <i>no tasks</i><br />
  <% else %>
    <table class="index_table">
      <tr>
        <th>Started</th>
        <th>Task</th>
        <th>Person</th>
        <th>Status</th>
        <th>Last contact</th>
      </tr>
      <% tasks.each do |t| %>
        <tr <%= raw( t.overdue? ? 'class="overdue"' : '' ) %>>
          <td><%= format_date t.created_at %></td>
          <td><%= link_to t.task_type.description, t %></td>
          <td><%= t.person.name %></td>
          <td><%= t.task_status.description %></td>
          <td>
            <%= format_date t.last_contact_attempt_made_at %>
            <% if t.overdue? %>
              <span class="overdue">(overdue)</span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

<% Message.order(:sort_order).all.each do |m| %>
  <div class="grouping_box">
    <h2><%= m.title %></h2>
    <div><%= format_plain_text m.content %></div>
  </div>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'Listing users') %>
<p><%= link_to '[create new user]', new_user_path, :class => :action %></p>

<%= render 'query', :query => @query %>

<div class="export_box">
  <h2>Export</h2>
  <%= link_to "Excel", users_path(:params => params.slice(:query), :format => :xlsx), :class => :download %>
</div>

<table class="index_table">
  <tr>
    <th>Name</th>
    <th>Username</th>
    <th>Active</th>
    <th></th>
    <% if logged_in_super_admin? %>
      <th></th>
    <% end %>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.person.name, user %></td>
      <td><%= user.username %></td>
      <td><%= user.active %></td>
      <td><%= link_to '[edit]', edit_user_path(user), :class => :action %></td>
      <% if logged_in_super_admin? %>
        <td><%= link_to '[destroy]', user, confirm: 'This will obliterate this record from the database...are you sure?', :method => :delete, :class => :action %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<% provide(:title, 'Create new user') %>

<%= render 'form' %>

<%= link_to '[go back to user list]', users_path, :class => :action %>

app/views/users/password.html.erb
<% provide(:title, "Change password for user #{@user.name}") %>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user == current_user %>
    <%= f.hidden_field :must_change_password, :value => false %>
  <% elsif logged_in_admin? %>
    <div class="field">
      <%= f.check_box :must_change_password %>
      <%= f.label :must_change_password, 'Must change password on next login' %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% if @user != current_user && logged_in_admin? %>
  <%= form_tag reset_password_user_path(@user), :action => :post do %>
    <%= submit_tag '[send password reset email]' %>
  <% end %>
<% end %>

<%= link_to '[cancel edit]', @user, :class => :action %> |
<%= link_to '[go back to user list]', users_path, :class => :action %>

app/views/users/show.html.erb
<% provide(:title, "User: #{@user.name}") %>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Active user:</b>
  <%= @user.active ? 'Yes' : 'No' %>
</p>

<p>
  <b>Administrator:</b>
  <%= @user.admin ? 'Yes' : 'No' %>
</p>

<%= render 'shared/person', :person => @user.person %>

<% show_finished = params[:show_finished] == 'true' %>
<% tasks = show_finished ? @user.tasks : @user.in_progress_tasks %>
<div class="grouping_box">
  <b>Showing <%= show_finished ? "all tasks" : "in-progress tasks" %></b>
  <%= link_to ( show_finished ? "[see only in-progress tasks]" : "[see finished tasks too]" ), user_path(@user, :show_finished => !show_finished ), :class => :action %>
  <br />
  <% if tasks.empty? %>
    <i>no tasks</i><br />
  <% else %>
    <table class="index_table">
      <tr>
        <th>Started</th>
        <th>Task</th>
        <th>Person</th>
        <th>Status</th>
        <th>Last contact</th>
      </tr>
      <% tasks.each do |t| %>
        <tr <%= raw( t.overdue? ? 'class="overdue"' : '' ) %>>
          <td><%= format_date t.created_at %></td>
          <td><%= link_to t.task_type.description, t %></td>
          <td><%= link_to t.person.name, t.person %></td>
          <td><%= t.task_status.description %></td>
          <td>
            <%= format_date t.last_contact_attempt_made_at %>
            <% if t.overdue? %>
              <span class="overdue">(overdue)</span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>


<%= link_to '[edit this user]', edit_user_path(@user), :class => :action %> |
<%= link_to '[change password]', password_user_path(@user), :class => :action %> |
<%= link_to '[go back to user list]', users_path, :class => :action %>

app/views/users/todo.html.erb
<% provide(:title, 'Connect app to-do list') %>

<style>
  .unfixed { color: #AA0000; }
  .fixed { color: #00AA00; text-decoration: line-through; }
</style>

<p>Legend: <span class="fixed">things that have been fixed</span> vs. <span class="unfixed">things that are not fixed yet</li></p>

<h2>General site usability</h2>
<ul>
  <li class="fixed">Add a site "feedback" link -&gt; email to Ryan</li>
  <li class="unfixed">Be able to view <b>all</b> notes for a person in one view</li>
  <li class="fixed">Don't complain when entering a person with no address</li>
  <li class="unfixed">Make finished tasks prominently indicate "finished"</li>
  <li class="unfixed">Add "forgot password" page</li>
  <li class="fixed">Add password change page</li>
  <li class="fixed">Don't require password change in order to update other "user" fields</li>
  <li class="fixed">Add person's phone/email/address to "task" page</li>
  <li class="unfixed">Allow converting a person into a user from the person's page</li>
  <li class="fixed">Make groups sort alphabetically in lists</li>
  <li class="fixed">Allow groups to be viewed clustered by-neighborhood</li>
  <li class="fixed">Add "search" functionality for users, people, and groups</li>
  <li class="fixed">Make links like "add to group" be less obtrusive</li>
  <li class="fixed">Allow tasks to be viewed and clustered by "start" date</li>
  <li class="fixed">Add "task start" and "most recent contact" to admin view of in-progress tasks</li>
  <li class="fixed">Fix the formatting of the "show group" page so that the description/restrictions fields don't run off the page</li>

  <li class="fixed">Add "useful links" (flowchart, facebook, etc.) to home page</li>
  <li class="fixed">Add phone/email to the group membership roster on the "show group" page</li>
  <li class="fixed">Make notes sort newest-first</li>
  <li class="fixed">Make the timestamp on a note display the time in the current timezone, not GMT</li>
  <li class="fixed">Remove the "destroy" links for groups/people/users. These things should be deactivated, not destroyed. (Note that the "destroy" links will still appear if logged in as the account named "admin", but not for any other accounts, including other administrative accounts. I've disabled the "admin" account so no one can log in as it...people should log in as themselves.)</li>
  <li class="fixed">Make people/users sort alphabetically in lists</li>
  <li class="unfixed">Search/sort/filter terms should have 'x' to remove and tooltips to describe them</li>
  <li class="unfixed">Postpone contact action needs a better way of being exposed</li>
  <li class="unfixed">Users should receive an email when a person is assigned to/from them (unless they did it)</li>
  <li class="unfixed">Admins should be able to edit the stuff users see on their "home" page</li>
  <li class="unfixed">Drop-downs for reassigning should show the group name and the contact. Also, should only show contacts for the appropriate group type</li>
</ul>


<h2>Information about groups</h2>
<ul>
  <li class="fixed">Allow a group to have separate "leader", "host" and "contact" people</li>
  <li class="fixed">Add a "neighborhood" field to the group</li>
  <li class="unfixed">Show the contact info for the contact person, and the address of the host on the group page</li>
  <li class="unfixed">Make the person for an in-progress connect task appear in the group list as "in-progress"</li>
</ul>


<h2>Information about people</h2>
<ul>
  <li class="unfixed">Make "remove from group" and "add to group" record a note</li>
  <li class="fixed">When recording a note, add the ability to indicate whether a contact attempt was made, and add "last contacted" info to the task</li>
  <li class="fixed">Add an "is a member?" checkbox</li>
</ul>


<h2>Task tracking</h2>
<ul>
  <li class="unfixed">Populate the 'next contact' field on creation</li>
  <li class="unfixed">Add a "sent City invite?" checkbox</li>
  <li class="unfixed">Add "service team agreement signed?" info (incl. covenant end date)</li>
</ul>