config/routes.rb
Connector::Application.routes.draw do
  root :to => 'users#home'

  resources :groups
  match '/groups/:group_id/members', :to => 'groups#add_member', :via => :post
  match '/groups/:group_id/members/:person_id', :to => 'groups#update_member', :via => :put
  match '/groups/:group_id/members/:person_id', :to => 'groups#remove_member', :via => :delete

  resources :regions

  resources :messages, :except => :show

  resources :people
  match '/people/:person_id/groups', :to => 'people#add_to_group', :via => :post
  match '/people/:person_id/groups/:group_id', :to => 'people#remove_from_group', :via => :delete

  resources :tasks
  match '/tasks/:task_id/notes', :to => 'tasks#add_note', :via => :post

  resources :task_types do
    resources :sub_task_types
  end

  resources :users do
    member do
      get 'password'
      post 'reset_password'
    end
  end
  match '/home', :to => 'users#home'
  match '/todo', :to => 'users#todo', :via => :get
  match '/email_overdue', :to => 'tasks#overdue', :via => :get

  resources :sessions, :only => [ :new, :create, :destroy ]
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_header.html.erb
<% if logged_in? %>
  <header class="navbar">
    <div class="container">
      <nav>
        <div><%= link_to_unless_current 'Home', home_path %></div>
        <div><%= link_to_unless_current 'People', people_path %></div>
        <div><%= link_to_unless_current 'Groups', groups_path %></div>
        <% if logged_in_admin? %>
          <hr />
          <div class="admin"><b>Admin</b></div>
          <div class="admin"><%= link_to_unless_current 'Users', users_path %></div>
          <div class="admin"><%= link_to_unless_current 'Tasks', tasks_path %></div>
          <div class="admin"><%= link_to_unless_current 'Define tasks', task_types_path %></div>
          <div class="admin"><%= link_to_unless_current 'Define regions', regions_path %></div>
          <div class="admin"><%= link_to_unless_current 'Edit homepage', messages_path %></div>
          <div class="admin"><%= link_to_unless_current 'Site to-do list', todo_path %></div>
          <div class="admin"><%= link_to_unless_current 'Email overdue task owners', email_overdue_path %></div>
        <% end %>
        <hr />
        <div><%= link_to_unless_current 'My profile', current_user %></div>
        <div><%= link_to 'Log out', logout_path, :method => :delete %></div>
      </nav>
    </div>
  </header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_page_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <h1 class="page_title"><%= page_title(yield(:title)) %></h1>
      <%= yield %>
    </div>

    <footer>
      Having a problem? <a href="mailto:<%= webmaster_email %>">Email the webmaster</a>.
      <!-- "Hi SendGrid! I own this website!" says jediry01@yahoo.com. -->
    </footer>
  </body>
</html>